export const ADD_PIZZA_SIZE = "ADD_PIZZA_SIZE";
export const ADD_PIZZA_TYPE = "ADD_PIZZA_TYPE";
export const ADD_PIZZA_TOPPINGS = "ADD_PIZZA_TOPPINGS";

export const RESET_PIZZA_ORDER = "RESET_PIZZA_ORDER";


export const DETAIL_LOADING_ACTION = "DETAIL_LOADING";
export const DETAIL_SET_ACTION = "DETAIL_SET";
export const DETAIL_ERROR_ACTION = "DETAIL_ERROR";
export const DETAIL_CLEAR_ACTION = "DETAIL_CLEAR";
